FROM node:24-slim

RUN apt-get update && \
    apt-get install -y redis-server  vim supervisor wget curl netcat-openbsd unzip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN curl -LsSf https://astral.sh/uv/install.sh | sh

ENV PATH="/root/.local/bin:$PATH"

RUN uv python install
RUN uv python install 3.11

RUN npm i -g -U opencode-ai

RUN npx oh-my-opencode install --no-tui --claude=no --openai=no --gemini=no --copilot=no

WORKDIR /tdd
COPY AGENTS.md /tdd/AGENTS.md
COPY pocket /tdd/pocket
